{% set name = "pnab" %}
{% set version = "1.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GT-NucleicAcids/pnab/archive/v{{ version }}.tar.gz
  sha256: effb9a0fc2e056090f9bbb0105a70e489f86d40aa354d23f348ee99d121dd482

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [linux]
  host:
    - eigen
    - python
    - openbabel =3.1.1
    - pybind11
  run:
    - python
    - numpy
    - openbabel =3.1.1
    - ipywidgets >=7.5, <8
    - nglview >=2.7, <3
    - pyyaml
    - jupyterlab =3
    - eigen  # [osx]
    - pybind  # [osx]
    - pybind11-global  # [osx]

test:
  imports:
    - pnab
  requires:
    - pytest
  commands:
    - call set BABEL_DATADIR=%PREFIX%\share\openbabel  # [win]
    - python -c "import pnab; pnab.test()"

about:
  home: https://github.com/GT-NucleicAcids/pnab
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: 'proto-Nucleic Acid Builder'

  description: |
    pnab, the proto-Nucleic Acid Builder, is a software tool for predicting
    the 3D structure of nucleic acid analogs.
  dev_url: https://github.com/GT-NucleicAcids/pnab

extra:
  recipe-maintainers:
    - alenaizan
